### ISSUE TITLE
Request for Model Parameters

### ISSUE THREAD

**Issue by exlaw** [xiaojunxu/learning-to-watermark-llm#1]
Congratulations on your excellent work!

 I have attempted to train a model following your script, but it seems that the model trained is not stable. May I inquire if it is possible for you to provide the trained model parameters such as watermarked opt-1.3B for research purposes?

**Comment by xiaojunxu** [comment]
Would you mind sharing the details of your training setting? The training should be stable based on our trials.

**Comment by exlaw** [comment]
Thank you for your reply. I have retrained it, and now I have a model that seems to work.
